name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  converttohtml:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_dir: '/posts'
          output_dir: '/posts'
      - uses: actions/upload-artifact@v4
        with:
          name: posts
          path: /posts/*
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to Droplet via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "."
          target: "/var/www/julianavalos.com/html"

      - name: Restart Nginx (optional, if needed)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          script: |
            sudo systemctl reload nginx
