name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Convert Markdown to HTML
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          for file in /posts/*.md; do
            [ -e "$file" ] || continue
            filename=$(basename "$file" .md)
            pandoc "$file" -o "/posts/$filename.html"
          done
      - name: Copy files to Droplet via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "."
          target: "/var/www/julianavalos.com/html"

      - name: Restart Nginx (optional, if needed)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          script: |
            sudo systemctl reload nginx
